// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Pool,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=100.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=87.500000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=22,HLS_SYN_FF=2647,HLS_SYN_LUT=4558}" *)

module Pool (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_st1_fsm_0 = 32'b1;
parameter    ap_ST_st2_fsm_1 = 32'b10;
parameter    ap_ST_st3_fsm_2 = 32'b100;
parameter    ap_ST_st4_fsm_3 = 32'b1000;
parameter    ap_ST_st5_fsm_4 = 32'b10000;
parameter    ap_ST_st6_fsm_5 = 32'b100000;
parameter    ap_ST_st7_fsm_6 = 32'b1000000;
parameter    ap_ST_st8_fsm_7 = 32'b10000000;
parameter    ap_ST_st9_fsm_8 = 32'b100000000;
parameter    ap_ST_st10_fsm_9 = 32'b1000000000;
parameter    ap_ST_st11_fsm_10 = 32'b10000000000;
parameter    ap_ST_st12_fsm_11 = 32'b100000000000;
parameter    ap_ST_st13_fsm_12 = 32'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 32'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 32'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 32'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 32'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 32'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 32'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 32'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 32'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 32'b1000000000000000000000;
parameter    ap_ST_pp0_stg0_fsm_22 = 32'b10000000000000000000000;
parameter    ap_ST_st33_fsm_23 = 32'b100000000000000000000000;
parameter    ap_ST_st34_fsm_24 = 32'b1000000000000000000000000;
parameter    ap_ST_st35_fsm_25 = 32'b10000000000000000000000000;
parameter    ap_ST_st36_fsm_26 = 32'b100000000000000000000000000;
parameter    ap_ST_st37_fsm_27 = 32'b1000000000000000000000000000;
parameter    ap_ST_st38_fsm_28 = 32'b10000000000000000000000000000;
parameter    ap_ST_st39_fsm_29 = 32'b100000000000000000000000000000;
parameter    ap_ST_st40_fsm_30 = 32'b1000000000000000000000000000000;
parameter    ap_ST_st41_fsm_31 = 32'b10000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv48_0 = 48'b000000000000000000000000000000000000000000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5BB1A2BC = 32'b1011011101100011010001010111100;
parameter    ap_const_lv32_DBB1A2BC = 32'b11011011101100011010001010111100;
parameter    ap_const_lv48_1 = 48'b1;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv5_2 = 5'b10;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (C_S_AXI_AXILITES_DATA_WIDTH / ap_const_int64_8);
parameter C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (C_M_AXI_GMEM_DATA_WIDTH / ap_const_int64_8);
parameter C_M_AXI_WSTRB_WIDTH = (C_M_AXI_DATA_WIDTH / ap_const_int64_8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1 : 0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1 : 0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1 : 0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1 : 0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1 : 0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1 : 0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1 : 0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1 : 0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1 : 0] m_axi_gmem_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1 : 0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1 : 0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1 : 0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_49;
reg    ap_ready;
wire   [15:0] CHin_V;
wire   [15:0] Hin_V;
wire   [15:0] Win_V;
wire   [7:0] Kx_V;
wire   [7:0] Ky_V;
wire   [1:0] mode_V;
wire   [31:0] feature_in;
wire   [31:0] feature_out;
reg    gmem_blk_n_AR;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_22;
reg    ap_sig_121;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg    ap_reg_ppiten_pp0_it6;
reg    ap_reg_ppiten_pp0_it7;
reg    ap_reg_ppiten_pp0_it8;
reg    ap_reg_ppiten_pp0_it9;
reg   [0:0] exitcond_flatten_reg_1253;
reg   [1:0] mode_V_read_reg_1045;
reg    gmem_blk_n_R;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7;
reg    gmem_blk_n_AW;
reg    ap_sig_cseq_ST_st35_fsm_25;
reg    ap_sig_179;
reg    gmem_blk_n_W;
reg    ap_sig_cseq_ST_st36_fsm_26;
reg    ap_sig_187;
reg    gmem_blk_n_B;
reg    ap_sig_cseq_ST_st41_fsm_31;
reg    ap_sig_195;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [31:0] gmem_ARADDR;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [15:0] indvar_flatten_reg_250;
reg   [7:0] i_op_assign_2_reg_261;
reg   [7:0] i_op_assign_3_reg_272;
reg   [31:0] sum_3_reg_283;
reg   [31:0] reg_340;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_sig_336;
reg   [7:0] Kx_V_read_reg_1051;
reg   [15:0] Win_V_read_reg_1056;
reg   [15:0] CHin_V_read_reg_1067;
reg   [29:0] tmp_1_reg_1073;
reg   [29:0] tmp_7_reg_1078;
wire   [15:0] lhs_V_fu_366_p1;
reg   [15:0] lhs_V_reg_1083;
wire   [15:0] rhs_V_fu_376_p1;
reg   [15:0] rhs_V_reg_1090;
wire   [48:0] tmp_7_cast_fu_386_p1;
reg   [48:0] tmp_7_cast_reg_1098;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_373;
wire    grp_fu_370_ap_done;
wire    grp_fu_380_ap_done;
wire   [47:0] tmp_32_cast_fu_389_p1;
reg   [47:0] tmp_32_cast_reg_1103;
wire   [15:0] grp_fu_370_p2;
reg   [15:0] r_V_14_reg_1110;
wire   [31:0] rhs_V_1_cast_fu_392_p1;
reg   [31:0] rhs_V_1_cast_reg_1115;
wire   [31:0] rhs_V_1_fu_396_p1;
reg   [31:0] rhs_V_1_reg_1121;
wire   [0:0] tmp_6_fu_399_p2;
reg   [0:0] tmp_6_reg_1130;
wire   [47:0] rhs_V_2_fu_404_p1;
reg   [47:0] rhs_V_2_reg_1134;
wire   [15:0] r_V_15_fu_407_p2;
reg   [15:0] r_V_15_reg_1139;
wire   [31:0] tmp_s_fu_332_p1;
reg   [31:0] tmp_s_reg_1144;
wire   [47:0] rhs_V_2_cast_fu_416_p1;
reg   [47:0] rhs_V_2_cast_reg_1149;
wire   [31:0] p_sum_fu_438_p3;
reg   [31:0] p_sum_reg_1155;
wire   [31:0] bound4_fu_979_p2;
reg   [31:0] bound4_reg_1160;
wire   [47:0] bound_fu_453_p2;
reg   [47:0] bound_reg_1165;
wire   [0:0] exitcond_mid_fu_459_p2;
reg   [0:0] exitcond_mid_reg_1170;
wire   [47:0] r_V_1_fu_472_p2;
reg   [47:0] r_V_1_reg_1175;
reg    ap_sig_cseq_ST_st21_fsm_20;
reg    ap_sig_415;
wire   [47:0] indvar_flatten_next1_fu_482_p2;
reg   [47:0] indvar_flatten_next1_reg_1183;
wire   [0:0] exitcond_flatten2_fu_488_p2;
reg   [0:0] exitcond_flatten2_reg_1188;
wire   [0:0] exitcond_flatten1_fu_477_p2;
wire   [0:0] exitcond_mid1_fu_498_p3;
reg   [0:0] exitcond_mid1_reg_1198;
wire   [15:0] i_op_assign_17_cast6_mid2_v_fu_518_p3;
reg   [15:0] i_op_assign_17_cast6_mid2_v_reg_1206;
reg    ap_sig_cseq_ST_st22_fsm_21;
reg    ap_sig_433;
wire   [31:0] i_op_assign_17_cast6_mid2_fu_525_p1;
reg   [31:0] i_op_assign_17_cast6_mid2_reg_1211;
wire   [47:0] rhs_V_7_cast_mid2_fu_529_p1;
reg   [47:0] rhs_V_7_cast_mid2_reg_1216;
wire  signed [15:0] i_op_assign_13_mid2_fu_555_p3;
reg  signed [15:0] i_op_assign_13_mid2_reg_1223;
wire   [15:0] tmp_1_mid2_fu_570_p3;
reg   [15:0] tmp_1_mid2_reg_1228;
wire   [47:0] r_V_1_mid2_fu_581_p3;
reg   [47:0] r_V_1_mid2_reg_1233;
wire   [15:0] i_op_assign_11_mid2_fu_588_p3;
reg   [15:0] i_op_assign_11_mid2_reg_1238;
wire   [31:0] i_op_assign_15_cast4_fu_595_p1;
reg   [31:0] i_op_assign_15_cast4_reg_1243;
wire  signed [15:0] tmp_5_fu_986_p2;
reg  signed [15:0] tmp_5_reg_1248;
wire   [0:0] exitcond_flatten_fu_599_p2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter4;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter5;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter6;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter8;
wire   [15:0] indvar_flatten_next_fu_604_p2;
wire   [7:0] r_V_4_mid2_v_v_v_v_v_v_fu_629_p3;
reg   [7:0] r_V_4_mid2_v_v_v_v_v_v_reg_1262;
reg   [31:0] gmem_addr_3_reg_1267;
reg   [31:0] gmem_addr_2_reg_1273;
reg   [31:0] gmem_addr_1_reg_1279;
wire   [7:0] jj_fu_742_p2;
wire   [31:0] grp_fu_327_p2;
reg    ap_sig_cseq_ST_st34_fsm_24;
reg    ap_sig_514;
reg   [31:0] gmem_addr_reg_1295;
wire   [15:0] j_fu_961_p2;
reg   [15:0] j_reg_1300;
wire   [31:0] indvar_flatten_next7_fu_972_p3;
reg   [31:0] indvar_flatten_next7_reg_1305;
reg   [47:0] indvar_flatten1_reg_191;
reg   [15:0] op_assign_8_reg_202;
reg   [31:0] indvar_flatten6_reg_214;
reg  signed [15:0] i_op_assign_s_reg_226;
reg   [15:0] i_op_assign_1_reg_238;
reg   [7:0] i_op_assign_2_phi_fu_265_p4;
reg   [31:0] sum_4_phi_fu_297_p8;
wire   [31:0] sum_2_fu_321_p2;
wire   [31:0] ap_reg_phiprechg_sum_4_reg_293pp0_it9;
wire   [31:0] feature_in_load_1_sum_3_fu_925_p3;
wire   [31:0] sum_3_feature_in_load_2_fu_832_p3;
reg   [31:0] sum_5_reg_309;
reg    ap_sig_cseq_ST_st33_fsm_23;
reg    ap_sig_579;
wire  signed [63:0] feature_in2_sum_cast_fu_686_p1;
wire  signed [63:0] feature_in2_sum5_cast_fu_709_p1;
wire  signed [63:0] feature_in2_sum6_cast_fu_732_p1;
wire   [63:0] feature_out4_sum_cast_fu_951_p1;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_reg_ioackin_gmem_AWREADY;
reg    ap_sig_ioackin_gmem_AWREADY;
reg    ap_reg_ioackin_gmem_WREADY;
reg    ap_sig_ioackin_gmem_WREADY;
wire   [31:0] tmp_s_fu_332_p0;
wire   [7:0] grp_fu_370_p1;
wire   [7:0] grp_fu_380_p1;
wire   [7:0] r_V_15_fu_407_p0;
wire   [7:0] r_V_15_fu_407_p1;
wire   [0:0] tmp_9_fu_419_p2;
wire   [0:0] tmp_2_fu_432_p2;
wire   [31:0] sum_fu_424_p3;
wire   [15:0] grp_fu_380_p2;
wire   [31:0] bound_fu_453_p0;
wire   [15:0] bound_fu_453_p1;
wire   [31:0] r_V_fu_1003_p2;
wire   [31:0] r_V_1_fu_472_p0;
wire   [15:0] r_V_1_fu_472_p1;
wire   [0:0] exitcond_fu_493_p2;
wire   [15:0] c_fu_512_p2;
wire  signed [15:0] tmp_11_fu_1025_p2;
wire   [15:0] i_op_assign_11_mid_fu_505_p3;
wire   [0:0] tmp_12_fu_551_p2;
(* use_dsp48 = "no" *) wire  signed [15:0] i_fu_545_p2;
wire   [31:0] r_V_mid1_fu_997_p2;
wire  signed [15:0] tmp_1_mid1_fu_991_p2;
wire   [15:0] tmp_1_mid_fu_533_p3;
wire   [15:0] r_V_1_mid1_fu_576_p0;
wire   [31:0] r_V_1_mid1_fu_576_p1;
wire   [47:0] r_V_1_mid1_fu_576_p2;
wire   [47:0] r_V_1_mid_fu_539_p3;
wire   [0:0] exitcond1_fu_610_p2;
wire   [7:0] ii7_fu_623_p2;
wire   [15:0] r_V_4_mid2_v_v_v_v_v_fu_637_p1;
wire   [15:0] r_V_4_mid2_v_v_v_v_fu_641_p2;
wire   [15:0] r_V_4_mid2_v_v_fu_650_p0;
wire  signed [15:0] r_V_4_mid2_v_v_fu_650_p1;
wire   [31:0] r_V_4_mid2_v_v_fu_650_p2;
wire  signed [31:0] r_V_4_mid2_fu_659_p0;
wire   [15:0] r_V_4_mid2_fu_659_p1;
wire   [7:0] i_op_assign_14_mid2_fu_615_p3;
wire   [15:0] tmp_10_fu_664_p1;
(* use_dsp48 = "no" *) wire  signed [15:0] w_V_fu_668_p2;
wire  signed [47:0] grp_fu_1037_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_13_fu_677_p2;
wire   [47:0] feature_in2_sum_fu_681_p2;
wire  signed [47:0] grp_fu_1009_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_10_fu_700_p2;
wire   [47:0] feature_in2_sum5_fu_704_p2;
wire  signed [47:0] grp_fu_1017_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_7_fu_723_p2;
wire   [47:0] feature_in2_sum6_fu_727_p2;
wire   [31:0] sum_3_to_int7_fu_748_p1;
wire   [31:0] feature_in_load_2_to_int_fu_766_p1;
wire   [7:0] tmp_22_fu_752_p4;
wire   [22:0] tmp_23_fu_762_p1;
wire   [0:0] notrhs_fu_790_p2;
wire   [0:0] notlhs_fu_784_p2;
wire   [7:0] tmp_24_fu_770_p4;
wire   [22:0] tmp_25_fu_780_p1;
wire   [0:0] notrhs9_fu_808_p2;
wire   [0:0] notlhs8_fu_802_p2;
wire   [0:0] tmp_26_fu_796_p2;
wire   [0:0] tmp_27_fu_814_p2;
wire   [0:0] tmp_28_fu_820_p2;
wire   [0:0] grp_fu_335_p2;
wire   [0:0] tmp_30_fu_826_p2;
wire   [31:0] sum_3_to_int_fu_841_p1;
wire   [31:0] feature_in_load_1_to_int_fu_859_p1;
wire   [7:0] tmp_13_fu_845_p4;
wire   [22:0] tmp_14_fu_855_p1;
wire   [0:0] notrhs1_fu_883_p2;
wire   [0:0] notlhs1_fu_877_p2;
wire   [7:0] tmp_15_fu_863_p4;
wire   [22:0] tmp_16_fu_873_p1;
wire   [0:0] notrhs2_fu_901_p2;
wire   [0:0] notlhs2_fu_895_p2;
wire   [0:0] tmp_17_fu_889_p2;
wire   [0:0] tmp_18_fu_907_p2;
wire   [0:0] tmp_19_fu_913_p2;
wire   [0:0] tmp_21_fu_919_p2;
wire   [31:0] grp_fu_1031_p3;
wire   [47:0] tmp1_cast_fu_934_p1;
wire   [47:0] tmp_8_fu_937_p2;
wire   [48:0] tmp_17_cast_cast_fu_942_p1;
wire   [48:0] feature_out4_sum_fu_946_p2;
wire   [31:0] indvar_flatten6_op_fu_966_p2;
wire   [15:0] bound4_fu_979_p0;
wire   [15:0] bound4_fu_979_p1;
wire   [7:0] tmp_5_fu_986_p0;
wire   [7:0] tmp_1_mid1_fu_991_p0;
wire   [15:0] r_V_mid1_fu_997_p0;
wire   [15:0] r_V_mid1_fu_997_p1;
wire   [15:0] r_V_fu_1003_p0;
wire   [15:0] r_V_fu_1003_p1;
wire   [15:0] grp_fu_1009_p1;
wire   [47:0] r_V_4_mid2_fu_659_p2;
wire   [15:0] grp_fu_1017_p1;
wire   [7:0] tmp_11_fu_1025_p1;
wire   [15:0] grp_fu_1031_p0;
wire   [15:0] grp_fu_1031_p1;
wire   [15:0] grp_fu_1031_p2;
wire   [15:0] grp_fu_1037_p1;
reg    grp_fu_370_ap_start;
reg    grp_fu_380_ap_start;
reg   [31:0] ap_NS_fsm;
wire   [31:0] bound4_fu_979_p00;
wire   [31:0] bound4_fu_979_p10;
wire   [47:0] bound_fu_453_p00;
wire   [47:0] bound_fu_453_p10;
wire   [15:0] grp_fu_370_p10;
wire   [15:0] grp_fu_380_p10;
wire   [47:0] r_V_1_fu_472_p00;
wire   [47:0] r_V_1_mid1_fu_576_p10;
wire   [31:0] r_V_fu_1003_p00;
wire   [31:0] r_V_mid1_fu_997_p10;
reg    ap_sig_1217;
reg    ap_sig_1219;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
#0 ap_reg_ppiten_pp0_it6 = 1'b0;
#0 ap_reg_ppiten_pp0_it7 = 1'b0;
#0 ap_reg_ppiten_pp0_it8 = 1'b0;
#0 ap_reg_ppiten_pp0_it9 = 1'b0;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem_WREADY = 1'b0;
end

Pool_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
Pool_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .CHin_V(CHin_V),
    .Hin_V(Hin_V),
    .Win_V(Win_V),
    .Kx_V(Kx_V),
    .Ky_V(Ky_V),
    .mode_V(mode_V),
    .feature_in(feature_in),
    .feature_out(feature_out)
);

Pool_gmem_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
Pool_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(1'b0),
    .I_ARLEN(ap_const_lv32_1),
    .I_ARSIZE(ap_const_lv3_0),
    .I_ARLOCK(ap_const_lv2_0),
    .I_ARCACHE(ap_const_lv4_0),
    .I_ARQOS(ap_const_lv4_0),
    .I_ARPROT(ap_const_lv3_0),
    .I_ARUSER(1'b0),
    .I_ARBURST(ap_const_lv2_0),
    .I_ARREGION(ap_const_lv4_0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_reg_1295),
    .I_AWID(1'b0),
    .I_AWLEN(ap_const_lv32_1),
    .I_AWSIZE(ap_const_lv3_0),
    .I_AWLOCK(ap_const_lv2_0),
    .I_AWCACHE(ap_const_lv4_0),
    .I_AWQOS(ap_const_lv4_0),
    .I_AWPROT(ap_const_lv3_0),
    .I_AWUSER(1'b0),
    .I_AWBURST(ap_const_lv2_0),
    .I_AWREGION(ap_const_lv4_0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(sum_5_reg_309),
    .I_WID(1'b0),
    .I_WUSER(1'b0),
    .I_WLAST(1'b0),
    .I_WSTRB(ap_const_lv4_F),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

Pool_fadd_32ns_32ns_32_1_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_fadd_32ns_32ns_32_1_full_dsp_U0(
    .din0(sum_3_reg_283),
    .din1(reg_340),
    .dout(sum_2_fu_321_p2)
);

Pool_fdiv_32ns_32ns_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_fdiv_32ns_32ns_32_2_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sum_3_reg_283),
    .din1(tmp_s_reg_1144),
    .ce(1'b1),
    .dout(grp_fu_327_p2)
);

Pool_sitofp_32ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_sitofp_32ns_32_1_U2(
    .din0(tmp_s_fu_332_p0),
    .dout(tmp_s_fu_332_p1)
);

Pool_fcmp_32ns_32ns_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
Pool_fcmp_32ns_32ns_1_1_U3(
    .din0(sum_3_reg_283),
    .din1(reg_340),
    .opcode(ap_const_lv5_2),
    .dout(grp_fu_335_p2)
);

Pool_udiv_16ns_8ns_16_20_seq #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
Pool_udiv_16ns_8ns_16_20_seq_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_370_ap_start),
    .done(grp_fu_370_ap_done),
    .din0(Win_V),
    .din1(grp_fu_370_p1),
    .ce(1'b1),
    .dout(grp_fu_370_p2)
);

Pool_udiv_16ns_8ns_16_20_seq #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
Pool_udiv_16ns_8ns_16_20_seq_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_380_ap_start),
    .done(grp_fu_380_ap_done),
    .din0(Hin_V),
    .din1(grp_fu_380_p1),
    .ce(1'b1),
    .dout(grp_fu_380_p2)
);

Pool_mul_mul_16ns_16ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Pool_mul_mul_16ns_16ns_32_1_U6(
    .din0(bound4_fu_979_p0),
    .din1(bound4_fu_979_p1),
    .dout(bound4_fu_979_p2)
);

Pool_mul_mul_8ns_16s_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
Pool_mul_mul_8ns_16s_16_1_U7(
    .din0(tmp_5_fu_986_p0),
    .din1(i_op_assign_13_mid2_fu_555_p3),
    .dout(tmp_5_fu_986_p2)
);

Pool_mul_mul_8ns_16s_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
Pool_mul_mul_8ns_16s_16_1_U8(
    .din0(tmp_1_mid1_fu_991_p0),
    .din1(i_fu_545_p2),
    .dout(tmp_1_mid1_fu_991_p2)
);

Pool_mul_mul_16ns_16ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Pool_mul_mul_16ns_16ns_32_1_U9(
    .din0(r_V_mid1_fu_997_p0),
    .din1(r_V_mid1_fu_997_p1),
    .dout(r_V_mid1_fu_997_p2)
);

Pool_mul_mul_16ns_16ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Pool_mul_mul_16ns_16ns_32_1_U10(
    .din0(r_V_fu_1003_p0),
    .din1(r_V_fu_1003_p1),
    .dout(r_V_fu_1003_p2)
);

Pool_mac_muladd_16s_16ns_48ns_48_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_16s_16ns_48ns_48_1_U11(
    .din0(w_V_fu_668_p2),
    .din1(grp_fu_1009_p1),
    .din2(r_V_4_mid2_fu_659_p2),
    .dout(grp_fu_1009_p3)
);

Pool_mac_muladd_16s_16ns_48ns_48_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_16s_16ns_48ns_48_1_U12(
    .din0(w_V_fu_668_p2),
    .din1(grp_fu_1017_p1),
    .din2(r_V_4_mid2_fu_659_p2),
    .dout(grp_fu_1017_p3)
);

Pool_mul_mul_16s_8ns_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
Pool_mul_mul_16s_8ns_16_1_U13(
    .din0(i_op_assign_s_reg_226),
    .din1(tmp_11_fu_1025_p1),
    .dout(tmp_11_fu_1025_p2)
);

Pool_mac_muladd_16ns_16ns_16ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Pool_mac_muladd_16ns_16ns_16ns_32_1_U14(
    .din0(grp_fu_1031_p0),
    .din1(grp_fu_1031_p1),
    .din2(grp_fu_1031_p2),
    .dout(grp_fu_1031_p3)
);

Pool_mac_muladd_16s_16ns_48ns_48_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_16s_16ns_48ns_48_1_U15(
    .din0(w_V_fu_668_p2),
    .din1(grp_fu_1037_p1),
    .din2(r_V_4_mid2_fu_659_p2),
    .dout(grp_fu_1037_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b0;
        end else if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b1 == gmem_ARREADY) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b1 == gmem_ARREADY) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b1 == gmem_ARREADY) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st35_fsm_25)) begin
            if (~(1'b0 == ap_sig_ioackin_gmem_AWREADY)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b0;
            end else if ((1'b1 == gmem_AWREADY)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st36_fsm_26)) begin
            if (~(1'b0 == ap_sig_ioackin_gmem_WREADY)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b0;
            end else if ((1'b1 == gmem_WREADY)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & ~(1'b0 == exitcond_flatten_fu_599_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
            ap_reg_ppiten_pp0_it9 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        i_op_assign_1_reg_238 <= j_reg_1300;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        i_op_assign_1_reg_238 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)))) begin
        i_op_assign_2_reg_261 <= r_V_4_mid2_v_v_v_v_v_v_reg_1262;
    end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        i_op_assign_2_reg_261 <= ap_const_lv8_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        i_op_assign_3_reg_272 <= jj_fu_742_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        i_op_assign_3_reg_272 <= ap_const_lv8_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        i_op_assign_s_reg_226 <= i_op_assign_11_mid2_reg_1238;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        i_op_assign_s_reg_226 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        indvar_flatten1_reg_191 <= indvar_flatten_next1_reg_1183;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        indvar_flatten1_reg_191 <= ap_const_lv48_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        indvar_flatten6_reg_214 <= indvar_flatten_next7_reg_1305;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        indvar_flatten6_reg_214 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        indvar_flatten_reg_250 <= indvar_flatten_next_fu_604_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        indvar_flatten_reg_250 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        op_assign_8_reg_202 <= i_op_assign_17_cast6_mid2_v_reg_1206;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        op_assign_8_reg_202 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it9) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter8))) begin
        sum_3_reg_283 <= sum_4_phi_fu_297_p8;
    end else if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        sum_3_reg_283 <= p_sum_reg_1155;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_reg_1130) & (1'b1 == ap_sig_cseq_ST_st33_fsm_23))) begin
        sum_5_reg_309 <= sum_3_reg_283;
    end else if (((1'b1 == ap_sig_cseq_ST_st34_fsm_24) & ~(1'b0 == tmp_6_reg_1130))) begin
        sum_5_reg_309 <= grp_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        CHin_V_read_reg_1067 <= CHin_V;
        Kx_V_read_reg_1051 <= Kx_V;
        Win_V_read_reg_1056 <= Win_V;
        lhs_V_reg_1083[7 : 0] <= lhs_V_fu_366_p1[7 : 0];
        mode_V_read_reg_1045 <= mode_V;
        rhs_V_reg_1090[7 : 0] <= rhs_V_fu_376_p1[7 : 0];
        tmp_1_reg_1073 <= {{feature_out[ap_const_lv32_1F : ap_const_lv32_2]}};
        tmp_7_reg_1078 <= {{feature_in[ap_const_lv32_1F : ap_const_lv32_2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)))) begin
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter1 <= exitcond_flatten_reg_1253;
        exitcond_flatten_reg_1253 <= exitcond_flatten_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) begin
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter2 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter1;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter3 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter2;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter4 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter3;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter5 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter4;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter6 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter5;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter6;
        ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter8 <= ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & ~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done)))) begin
        bound4_reg_1160 <= bound4_fu_979_p2;
        bound_reg_1165 <= bound_fu_453_p2;
        exitcond_mid_reg_1170 <= exitcond_mid_fu_459_p2;
        p_sum_reg_1155[5 : 2] <= p_sum_fu_438_p3[5 : 2];
p_sum_reg_1155[7] <= p_sum_fu_438_p3[7];
p_sum_reg_1155[9] <= p_sum_fu_438_p3[9];
p_sum_reg_1155[13] <= p_sum_fu_438_p3[13];
p_sum_reg_1155[16 : 15] <= p_sum_fu_438_p3[16 : 15];
p_sum_reg_1155[21 : 20] <= p_sum_fu_438_p3[21 : 20];
p_sum_reg_1155[25 : 23] <= p_sum_fu_438_p3[25 : 23];
p_sum_reg_1155[28 : 27] <= p_sum_fu_438_p3[28 : 27];
p_sum_reg_1155[31 : 30] <= p_sum_fu_438_p3[31 : 30];
        r_V_14_reg_1110 <= grp_fu_370_p2;
        r_V_15_reg_1139 <= r_V_15_fu_407_p2;
        rhs_V_1_cast_reg_1115[15 : 0] <= rhs_V_1_cast_fu_392_p1[15 : 0];
        rhs_V_1_reg_1121[15 : 0] <= rhs_V_1_fu_396_p1[15 : 0];
        rhs_V_2_cast_reg_1149[15 : 0] <= rhs_V_2_cast_fu_416_p1[15 : 0];
        rhs_V_2_reg_1134[15 : 0] <= rhs_V_2_fu_404_p1[15 : 0];
        tmp_32_cast_reg_1103[29 : 0] <= tmp_32_cast_fu_389_p1[29 : 0];
        tmp_6_reg_1130 <= tmp_6_fu_399_p2;
        tmp_7_cast_reg_1098[29 : 0] <= tmp_7_cast_fu_386_p1[29 : 0];
        tmp_s_reg_1144 <= tmp_s_fu_332_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st21_fsm_20) & (1'b0 == exitcond_flatten1_fu_477_p2))) begin
        exitcond_flatten2_reg_1188 <= exitcond_flatten2_fu_488_p2;
        exitcond_mid1_reg_1198 <= exitcond_mid1_fu_498_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (mode_V_read_reg_1045 == ap_const_lv2_0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        gmem_addr_1_reg_1279 <= feature_in2_sum6_cast_fu_732_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (mode_V_read_reg_1045 == ap_const_lv2_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        gmem_addr_2_reg_1273 <= feature_in2_sum5_cast_fu_709_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (mode_V_read_reg_1045 == ap_const_lv2_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        gmem_addr_3_reg_1267 <= feature_in2_sum_cast_fu_686_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st34_fsm_24)) begin
        gmem_addr_reg_1295 <= feature_out4_sum_cast_fu_951_p1;
        indvar_flatten_next7_reg_1305 <= indvar_flatten_next7_fu_972_p3;
        j_reg_1300 <= j_fu_961_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        i_op_assign_11_mid2_reg_1238 <= i_op_assign_11_mid2_fu_588_p3;
        i_op_assign_13_mid2_reg_1223 <= i_op_assign_13_mid2_fu_555_p3;
        i_op_assign_15_cast4_reg_1243[15 : 0] <= i_op_assign_15_cast4_fu_595_p1[15 : 0];
        i_op_assign_17_cast6_mid2_reg_1211[15 : 0] <= i_op_assign_17_cast6_mid2_fu_525_p1[15 : 0];
        i_op_assign_17_cast6_mid2_v_reg_1206 <= i_op_assign_17_cast6_mid2_v_fu_518_p3;
        r_V_1_mid2_reg_1233 <= r_V_1_mid2_fu_581_p3;
        rhs_V_7_cast_mid2_reg_1216[15 : 0] <= rhs_V_7_cast_mid2_fu_529_p1[15 : 0];
        tmp_1_mid2_reg_1228 <= tmp_1_mid2_fu_570_p3;
        tmp_5_reg_1248 <= tmp_5_fu_986_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        indvar_flatten_next1_reg_1183 <= indvar_flatten_next1_fu_482_p2;
        r_V_1_reg_1175 <= r_V_1_fu_472_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & (1'b0 == exitcond_flatten_fu_599_p2))) begin
        r_V_4_mid2_v_v_v_v_v_v_reg_1262 <= r_V_4_mid2_v_v_v_v_v_v_fu_629_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))))) begin
        reg_340 <= gmem_RDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st21_fsm_20) & ~(1'b0 == exitcond_flatten1_fu_477_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st21_fsm_20) & ~(1'b0 == exitcond_flatten1_fu_477_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_121) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_22 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_22 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_49) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_373) begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_415) begin
        ap_sig_cseq_ST_st21_fsm_20 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_20 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_433) begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_579) begin
        ap_sig_cseq_ST_st33_fsm_23 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_23 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_514) begin
        ap_sig_cseq_ST_st34_fsm_24 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_24 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_179) begin
        ap_sig_cseq_ST_st35_fsm_25 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st35_fsm_25 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_187) begin
        ap_sig_cseq_ST_st36_fsm_26 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st36_fsm_26 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_195) begin
        ap_sig_cseq_ST_st41_fsm_31 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st41_fsm_31 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_AWREADY)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_WREADY)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (ap_sig_1217) begin
        if ((mode_V_read_reg_1045 == ap_const_lv2_0)) begin
            gmem_ARADDR = gmem_addr_1_reg_1279;
        end else if ((mode_V_read_reg_1045 == ap_const_lv2_1)) begin
            gmem_ARADDR = gmem_addr_2_reg_1273;
        end else if ((mode_V_read_reg_1045 == ap_const_lv2_2)) begin
            gmem_ARADDR = gmem_addr_3_reg_1267;
        end else begin
            gmem_ARADDR = 'bx;
        end
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st35_fsm_25) & (1'b0 == ap_reg_ioackin_gmem_AWREADY))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st41_fsm_31) & ~(gmem_BVALID == 1'b0))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336))))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st36_fsm_26) & (1'b0 == ap_reg_ioackin_gmem_WREADY))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st35_fsm_25)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st41_fsm_31)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it8) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7)) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_1)) | ((1'b1 == ap_reg_ppiten_pp0_it8) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_2)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st36_fsm_26)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        grp_fu_370_ap_start = 1'b1;
    end else begin
        grp_fu_370_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        grp_fu_380_ap_start = 1'b1;
    end else begin
        grp_fu_380_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0))) begin
        i_op_assign_2_phi_fu_265_p4 = r_V_4_mid2_v_v_v_v_v_v_reg_1262;
    end else begin
        i_op_assign_2_phi_fu_265_p4 = i_op_assign_2_reg_261;
    end
end

always @ (*) begin
    if (ap_sig_1219) begin
        if ((mode_V_read_reg_1045 == ap_const_lv2_2)) begin
            sum_4_phi_fu_297_p8 = sum_3_feature_in_load_2_fu_832_p3;
        end else if ((mode_V_read_reg_1045 == ap_const_lv2_1)) begin
            sum_4_phi_fu_297_p8 = feature_in_load_1_sum_3_fu_925_p3;
        end else if ((mode_V_read_reg_1045 == ap_const_lv2_3)) begin
            sum_4_phi_fu_297_p8 = sum_3_reg_283;
        end else if ((mode_V_read_reg_1045 == ap_const_lv2_0)) begin
            sum_4_phi_fu_297_p8 = sum_2_fu_321_p2;
        end else begin
            sum_4_phi_fu_297_p8 = ap_reg_phiprechg_sum_4_reg_293pp0_it9;
        end
    end else begin
        sum_4_phi_fu_297_p8 = ap_reg_phiprechg_sum_4_reg_293pp0_it9;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : begin
            if (~((1'b0 == grp_fu_370_ap_done) | (1'b0 == grp_fu_380_ap_done))) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st21_fsm_20 : begin
            if (~(1'b0 == exitcond_flatten1_fu_477_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end
        end
        ap_ST_st22_fsm_21 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_22;
        end
        ap_ST_pp0_stg0_fsm_22 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it9) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & ~(1'b1 == ap_reg_ppiten_pp0_it8))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_22;
            end else if (((1'b1 == ap_reg_ppiten_pp0_it9) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)) | ((exitcond_flatten_reg_1253 == 1'b0) & (mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_sig_ioackin_gmem_ARREADY)))) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336)) & ~(1'b1 == ap_reg_ppiten_pp0_it8))) begin
                ap_NS_fsm = ap_ST_st33_fsm_23;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_22;
            end
        end
        ap_ST_st33_fsm_23 : begin
            ap_NS_fsm = ap_ST_st34_fsm_24;
        end
        ap_ST_st34_fsm_24 : begin
            ap_NS_fsm = ap_ST_st35_fsm_25;
        end
        ap_ST_st35_fsm_25 : begin
            if (~(1'b0 == ap_sig_ioackin_gmem_AWREADY)) begin
                ap_NS_fsm = ap_ST_st36_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st35_fsm_25;
            end
        end
        ap_ST_st36_fsm_26 : begin
            if (~(1'b0 == ap_sig_ioackin_gmem_WREADY)) begin
                ap_NS_fsm = ap_ST_st37_fsm_27;
            end else begin
                ap_NS_fsm = ap_ST_st36_fsm_26;
            end
        end
        ap_ST_st37_fsm_27 : begin
            ap_NS_fsm = ap_ST_st38_fsm_28;
        end
        ap_ST_st38_fsm_28 : begin
            ap_NS_fsm = ap_ST_st39_fsm_29;
        end
        ap_ST_st39_fsm_29 : begin
            ap_NS_fsm = ap_ST_st40_fsm_30;
        end
        ap_ST_st40_fsm_30 : begin
            ap_NS_fsm = ap_ST_st41_fsm_31;
        end
        ap_ST_st41_fsm_31 : begin
            if (~(gmem_BVALID == 1'b0)) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st41_fsm_31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_sum_4_reg_293pp0_it9 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_121 = (1'b1 == ap_CS_fsm[ap_const_lv32_16]);
end

always @ (*) begin
    ap_sig_1217 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_22) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_1253 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_336) & (1'b0 == ap_reg_ioackin_gmem_ARREADY));
end

always @ (*) begin
    ap_sig_1219 = ((1'b1 == ap_reg_ppiten_pp0_it9) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter8));
end

always @ (*) begin
    ap_sig_179 = (1'b1 == ap_CS_fsm[ap_const_lv32_19]);
end

always @ (*) begin
    ap_sig_187 = (1'b1 == ap_CS_fsm[ap_const_lv32_1A]);
end

always @ (*) begin
    ap_sig_195 = (1'b1 == ap_CS_fsm[ap_const_lv32_1F]);
end

always @ (*) begin
    ap_sig_336 = (((1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_2) & (gmem_RVALID == 1'b0)) | ((1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (mode_V_read_reg_1045 == ap_const_lv2_1) & (gmem_RVALID == 1'b0)) | ((mode_V_read_reg_1045 == ap_const_lv2_0) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1253_pp0_iter7) & (gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_sig_373 = (1'b1 == ap_CS_fsm[ap_const_lv32_13]);
end

always @ (*) begin
    ap_sig_415 = (1'b1 == ap_CS_fsm[ap_const_lv32_14]);
end

always @ (*) begin
    ap_sig_433 = (1'b1 == ap_CS_fsm[ap_const_lv32_15]);
end

always @ (*) begin
    ap_sig_49 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_514 = (1'b1 == ap_CS_fsm[ap_const_lv32_18]);
end

always @ (*) begin
    ap_sig_579 = (1'b1 == ap_CS_fsm[ap_const_lv32_17]);
end

assign bound4_fu_979_p0 = bound4_fu_979_p00;

assign bound4_fu_979_p00 = grp_fu_370_p2;

assign bound4_fu_979_p1 = bound4_fu_979_p10;

assign bound4_fu_979_p10 = grp_fu_380_p2;

assign bound_fu_453_p0 = bound_fu_453_p00;

assign bound_fu_453_p00 = bound4_fu_979_p2;

assign bound_fu_453_p1 = bound_fu_453_p10;

assign bound_fu_453_p10 = CHin_V_read_reg_1067;

assign bound_fu_453_p2 = (bound_fu_453_p0 * bound_fu_453_p1);

assign c_fu_512_p2 = (op_assign_8_reg_202 + ap_const_lv16_1);

assign exitcond1_fu_610_p2 = ((i_op_assign_3_reg_272 == Kx_V_read_reg_1051) ? 1'b1 : 1'b0);

assign exitcond_flatten1_fu_477_p2 = ((indvar_flatten1_reg_191 == bound_reg_1165) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_488_p2 = ((indvar_flatten6_reg_214 == bound4_reg_1160) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_599_p2 = ((indvar_flatten_reg_250 == r_V_15_reg_1139) ? 1'b1 : 1'b0);

assign exitcond_fu_493_p2 = ((i_op_assign_1_reg_238 == r_V_14_reg_1110) ? 1'b1 : 1'b0);

assign exitcond_mid1_fu_498_p3 = ((exitcond_flatten2_fu_488_p2[0:0] === 1'b1) ? exitcond_mid_reg_1170 : exitcond_fu_493_p2);

assign exitcond_mid_fu_459_p2 = ((grp_fu_370_p2 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign feature_in2_sum5_cast_fu_709_p1 = $signed(feature_in2_sum5_fu_704_p2);

assign feature_in2_sum5_fu_704_p2 = (tmp_32_cast_reg_1103 + r_V_10_fu_700_p2);

assign feature_in2_sum6_cast_fu_732_p1 = $signed(feature_in2_sum6_fu_727_p2);

assign feature_in2_sum6_fu_727_p2 = (r_V_7_fu_723_p2 + tmp_32_cast_reg_1103);

assign feature_in2_sum_cast_fu_686_p1 = $signed(feature_in2_sum_fu_681_p2);

assign feature_in2_sum_fu_681_p2 = (tmp_32_cast_reg_1103 + r_V_13_fu_677_p2);

assign feature_in_load_1_sum_3_fu_925_p3 = ((tmp_21_fu_919_p2[0:0] === 1'b1) ? reg_340 : sum_3_reg_283);

assign feature_in_load_1_to_int_fu_859_p1 = reg_340;

assign feature_in_load_2_to_int_fu_766_p1 = reg_340;

assign feature_out4_sum_cast_fu_951_p1 = feature_out4_sum_fu_946_p2;

assign feature_out4_sum_fu_946_p2 = (tmp_17_cast_cast_fu_942_p1 + tmp_7_cast_reg_1098);

assign grp_fu_1009_p1 = rhs_V_1_reg_1121;

assign grp_fu_1017_p1 = rhs_V_1_reg_1121;

assign grp_fu_1031_p0 = rhs_V_1_reg_1121;

assign grp_fu_1031_p1 = i_op_assign_15_cast4_reg_1243;

assign grp_fu_1031_p2 = i_op_assign_17_cast6_mid2_reg_1211;

assign grp_fu_1037_p1 = rhs_V_1_reg_1121;

assign grp_fu_370_p1 = grp_fu_370_p10;

assign grp_fu_370_p10 = Kx_V;

assign grp_fu_380_p1 = grp_fu_380_p10;

assign grp_fu_380_p10 = Ky_V;

assign i_fu_545_p2 = (i_op_assign_11_mid_fu_505_p3 + ap_const_lv16_1);

assign i_op_assign_11_mid2_fu_588_p3 = ((exitcond_mid1_reg_1198[0:0] === 1'b1) ? i_fu_545_p2 : i_op_assign_11_mid_fu_505_p3);

assign i_op_assign_11_mid_fu_505_p3 = ((exitcond_flatten2_reg_1188[0:0] === 1'b1) ? ap_const_lv16_0 : i_op_assign_s_reg_226);

assign i_op_assign_13_mid2_fu_555_p3 = ((tmp_12_fu_551_p2[0:0] === 1'b1) ? ap_const_lv16_0 : i_op_assign_1_reg_238);

assign i_op_assign_14_mid2_fu_615_p3 = ((exitcond1_fu_610_p2[0:0] === 1'b1) ? ap_const_lv8_0 : i_op_assign_3_reg_272);

assign i_op_assign_15_cast4_fu_595_p1 = $unsigned(i_op_assign_13_mid2_fu_555_p3);

assign i_op_assign_17_cast6_mid2_fu_525_p1 = i_op_assign_17_cast6_mid2_v_fu_518_p3;

assign i_op_assign_17_cast6_mid2_v_fu_518_p3 = ((exitcond_flatten2_reg_1188[0:0] === 1'b1) ? c_fu_512_p2 : op_assign_8_reg_202);

assign ii7_fu_623_p2 = (i_op_assign_2_phi_fu_265_p4 + ap_const_lv8_1);

assign indvar_flatten6_op_fu_966_p2 = (indvar_flatten6_reg_214 + ap_const_lv32_1);

assign indvar_flatten_next1_fu_482_p2 = (indvar_flatten1_reg_191 + ap_const_lv48_1);

assign indvar_flatten_next7_fu_972_p3 = ((exitcond_flatten2_reg_1188[0:0] === 1'b1) ? ap_const_lv32_1 : indvar_flatten6_op_fu_966_p2);

assign indvar_flatten_next_fu_604_p2 = (indvar_flatten_reg_250 + ap_const_lv16_1);

assign j_fu_961_p2 = ($signed(i_op_assign_13_mid2_reg_1223) + $signed(ap_const_lv16_1));

assign jj_fu_742_p2 = (i_op_assign_14_mid2_fu_615_p3 + ap_const_lv8_1);

assign lhs_V_fu_366_p1 = Kx_V;

assign notlhs1_fu_877_p2 = ((tmp_13_fu_845_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notlhs2_fu_895_p2 = ((tmp_15_fu_863_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notlhs8_fu_802_p2 = ((tmp_24_fu_770_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notlhs_fu_784_p2 = ((tmp_22_fu_752_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notrhs1_fu_883_p2 = ((tmp_14_fu_855_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign notrhs2_fu_901_p2 = ((tmp_16_fu_873_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign notrhs9_fu_808_p2 = ((tmp_25_fu_780_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign notrhs_fu_790_p2 = ((tmp_23_fu_762_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign p_sum_fu_438_p3 = ((tmp_2_fu_432_p2[0:0] === 1'b1) ? sum_fu_424_p3 : ap_const_lv32_DBB1A2BC);

assign r_V_10_fu_700_p2 = ($signed(rhs_V_7_cast_mid2_reg_1216) + $signed(grp_fu_1009_p3));

assign r_V_13_fu_677_p2 = ($signed(rhs_V_7_cast_mid2_reg_1216) + $signed(grp_fu_1037_p3));

assign r_V_15_fu_407_p0 = lhs_V_reg_1083;

assign r_V_15_fu_407_p1 = rhs_V_reg_1090;

assign r_V_15_fu_407_p2 = (r_V_15_fu_407_p0 * r_V_15_fu_407_p1);

assign r_V_1_fu_472_p0 = r_V_1_fu_472_p00;

assign r_V_1_fu_472_p00 = r_V_fu_1003_p2;

assign r_V_1_fu_472_p1 = rhs_V_2_cast_reg_1149;

assign r_V_1_fu_472_p2 = (r_V_1_fu_472_p0 * r_V_1_fu_472_p1);

assign r_V_1_mid1_fu_576_p0 = rhs_V_2_cast_reg_1149;

assign r_V_1_mid1_fu_576_p1 = r_V_1_mid1_fu_576_p10;

assign r_V_1_mid1_fu_576_p10 = r_V_mid1_fu_997_p2;

assign r_V_1_mid1_fu_576_p2 = (r_V_1_mid1_fu_576_p0 * r_V_1_mid1_fu_576_p1);

assign r_V_1_mid2_fu_581_p3 = ((exitcond_mid1_reg_1198[0:0] === 1'b1) ? r_V_1_mid1_fu_576_p2 : r_V_1_mid_fu_539_p3);

assign r_V_1_mid_fu_539_p3 = ((exitcond_flatten2_reg_1188[0:0] === 1'b1) ? ap_const_lv48_0 : r_V_1_reg_1175);

assign r_V_4_mid2_fu_659_p0 = r_V_4_mid2_v_v_fu_650_p2;

assign r_V_4_mid2_fu_659_p1 = rhs_V_2_reg_1134;

assign r_V_4_mid2_fu_659_p2 = ($signed(r_V_4_mid2_fu_659_p0) * $signed({{1'b0}, {r_V_4_mid2_fu_659_p1}}));

assign r_V_4_mid2_v_v_fu_650_p0 = rhs_V_1_reg_1121;

assign r_V_4_mid2_v_v_fu_650_p1 = r_V_4_mid2_v_v_v_v_fu_641_p2;

assign r_V_4_mid2_v_v_fu_650_p2 = ($signed({{1'b0}, {r_V_4_mid2_v_v_fu_650_p0}}) * $signed(r_V_4_mid2_v_v_fu_650_p1));

assign r_V_4_mid2_v_v_v_v_fu_641_p2 = (r_V_4_mid2_v_v_v_v_v_fu_637_p1 + tmp_1_mid2_reg_1228);

assign r_V_4_mid2_v_v_v_v_v_fu_637_p1 = r_V_4_mid2_v_v_v_v_v_v_fu_629_p3;

assign r_V_4_mid2_v_v_v_v_v_v_fu_629_p3 = ((exitcond1_fu_610_p2[0:0] === 1'b1) ? ii7_fu_623_p2 : i_op_assign_2_phi_fu_265_p4);

assign r_V_7_fu_723_p2 = ($signed(rhs_V_7_cast_mid2_reg_1216) + $signed(grp_fu_1017_p3));

assign r_V_fu_1003_p0 = r_V_fu_1003_p00;

assign r_V_fu_1003_p00 = $unsigned(i_op_assign_s_reg_226);

assign r_V_fu_1003_p1 = rhs_V_1_cast_reg_1115;

assign r_V_mid1_fu_997_p0 = rhs_V_1_cast_reg_1115;

assign r_V_mid1_fu_997_p1 = r_V_mid1_fu_997_p10;

assign r_V_mid1_fu_997_p10 = $unsigned(i_fu_545_p2);

assign rhs_V_1_cast_fu_392_p1 = grp_fu_370_p2;

assign rhs_V_1_fu_396_p1 = CHin_V_read_reg_1067;

assign rhs_V_2_cast_fu_416_p1 = CHin_V_read_reg_1067;

assign rhs_V_2_fu_404_p1 = Win_V_read_reg_1056;

assign rhs_V_7_cast_mid2_fu_529_p1 = i_op_assign_17_cast6_mid2_v_fu_518_p3;

assign rhs_V_fu_376_p1 = Ky_V;

assign sum_3_feature_in_load_2_fu_832_p3 = ((tmp_30_fu_826_p2[0:0] === 1'b1) ? sum_3_reg_283 : reg_340);

assign sum_3_to_int7_fu_748_p1 = sum_3_reg_283;

assign sum_3_to_int_fu_841_p1 = sum_3_reg_283;

assign sum_fu_424_p3 = ((tmp_6_fu_399_p2[0:0] === 1'b1) ? ap_const_lv32_0 : ap_const_lv32_5BB1A2BC);

assign tmp1_cast_fu_934_p1 = grp_fu_1031_p3;

assign tmp_10_fu_664_p1 = i_op_assign_14_mid2_fu_615_p3;

assign tmp_11_fu_1025_p1 = rhs_V_reg_1090;

assign tmp_12_fu_551_p2 = (exitcond_mid1_reg_1198 | exitcond_flatten2_reg_1188);

assign tmp_13_fu_845_p4 = {{sum_3_to_int_fu_841_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_14_fu_855_p1 = sum_3_to_int_fu_841_p1[22:0];

assign tmp_15_fu_863_p4 = {{feature_in_load_1_to_int_fu_859_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_16_fu_873_p1 = feature_in_load_1_to_int_fu_859_p1[22:0];

assign tmp_17_cast_cast_fu_942_p1 = tmp_8_fu_937_p2;

assign tmp_17_fu_889_p2 = (notrhs1_fu_883_p2 | notlhs1_fu_877_p2);

assign tmp_18_fu_907_p2 = (notrhs2_fu_901_p2 | notlhs2_fu_895_p2);

assign tmp_19_fu_913_p2 = (tmp_17_fu_889_p2 & tmp_18_fu_907_p2);

assign tmp_1_mid1_fu_991_p0 = rhs_V_reg_1090;

assign tmp_1_mid2_fu_570_p3 = ((exitcond_mid1_reg_1198[0:0] === 1'b1) ? tmp_1_mid1_fu_991_p2 : tmp_1_mid_fu_533_p3);

assign tmp_1_mid_fu_533_p3 = ((exitcond_flatten2_reg_1188[0:0] === 1'b1) ? ap_const_lv16_0 : tmp_11_fu_1025_p2);

assign tmp_21_fu_919_p2 = (tmp_19_fu_913_p2 & grp_fu_335_p2);

assign tmp_22_fu_752_p4 = {{sum_3_to_int7_fu_748_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_23_fu_762_p1 = sum_3_to_int7_fu_748_p1[22:0];

assign tmp_24_fu_770_p4 = {{feature_in_load_2_to_int_fu_766_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_25_fu_780_p1 = feature_in_load_2_to_int_fu_766_p1[22:0];

assign tmp_26_fu_796_p2 = (notrhs_fu_790_p2 | notlhs_fu_784_p2);

assign tmp_27_fu_814_p2 = (notrhs9_fu_808_p2 | notlhs8_fu_802_p2);

assign tmp_28_fu_820_p2 = (tmp_26_fu_796_p2 & tmp_27_fu_814_p2);

assign tmp_2_fu_432_p2 = (tmp_6_fu_399_p2 | tmp_9_fu_419_p2);

assign tmp_30_fu_826_p2 = (tmp_28_fu_820_p2 & grp_fu_335_p2);

assign tmp_32_cast_fu_389_p1 = tmp_7_reg_1078;

assign tmp_5_fu_986_p0 = lhs_V_reg_1083;

assign tmp_6_fu_399_p2 = ((mode_V_read_reg_1045 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_7_cast_fu_386_p1 = tmp_1_reg_1073;

assign tmp_8_fu_937_p2 = (r_V_1_mid2_reg_1233 + tmp1_cast_fu_934_p1);

assign tmp_9_fu_419_p2 = ((mode_V_read_reg_1045 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign tmp_s_fu_332_p0 = r_V_15_fu_407_p2;

assign w_V_fu_668_p2 = ($signed(tmp_10_fu_664_p1) + $signed(tmp_5_reg_1248));

always @ (posedge ap_clk) begin
    lhs_V_reg_1083[15:8] <= 8'b00000000;
    rhs_V_reg_1090[15:8] <= 8'b00000000;
    tmp_7_cast_reg_1098[48:30] <= 19'b0000000000000000000;
    tmp_32_cast_reg_1103[47:30] <= 18'b000000000000000000;
    rhs_V_1_cast_reg_1115[31:16] <= 16'b0000000000000000;
    rhs_V_1_reg_1121[31:16] <= 16'b0000000000000000;
    rhs_V_2_reg_1134[47:16] <= 32'b00000000000000000000000000000000;
    rhs_V_2_cast_reg_1149[47:16] <= 32'b00000000000000000000000000000000;
    p_sum_reg_1155[1:0] <= 2'b00;
    p_sum_reg_1155[6:6] <= 1'b0;
    p_sum_reg_1155[8:8] <= 1'b0;
    p_sum_reg_1155[12:10] <= 3'b000;
    p_sum_reg_1155[14:14] <= 1'b0;
    p_sum_reg_1155[19:17] <= 3'b000;
    p_sum_reg_1155[22:22] <= 1'b0;
    p_sum_reg_1155[26:26] <= 1'b0;
    p_sum_reg_1155[29] <= 1'b0;
    i_op_assign_17_cast6_mid2_reg_1211[31:16] <= 16'b0000000000000000;
    rhs_V_7_cast_mid2_reg_1216[47:16] <= 32'b00000000000000000000000000000000;
    i_op_assign_15_cast4_reg_1243[31:16] <= 16'b0000000000000000;
end

endmodule //Pool
