# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynq/pynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq || ORIG_REF_NAME==pynq} -quiet] -quiet

# IP: bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_processing_system7_0_0 || ORIG_REF_NAME==pynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_Conv_0_0/pynq_Conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_Conv_0_0 || ORIG_REF_NAME==pynq_Conv_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_Pool_0_0/pynq_Pool_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_Pool_0_0 || ORIG_REF_NAME==pynq_Pool_0_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_axi_mem_intercon_0/pynq_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_axi_mem_intercon_0 || ORIG_REF_NAME==pynq_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_rst_ps7_0_50M_0/pynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==pynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_axi_mem_intercon_1_0/pynq_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_axi_mem_intercon_1_0 || ORIG_REF_NAME==pynq_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_xbar_0/pynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_xbar_0 || ORIG_REF_NAME==pynq_xbar_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_ps7_0_axi_periph_0/pynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==pynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_pc_0 || ORIG_REF_NAME==pynq_auto_pc_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_us_0 || ORIG_REF_NAME==pynq_auto_us_0} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_pc_1 || ORIG_REF_NAME==pynq_auto_pc_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_us_1 || ORIG_REF_NAME==pynq_auto_us_1} -quiet] -quiet

# IP: bd/pynq/ip/pynq_auto_pc_2/pynq_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_pc_2 || ORIG_REF_NAME==pynq_auto_pc_2} -quiet] -quiet

# XDC: bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_processing_system7_0_0 || ORIG_REF_NAME==pynq_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynq/ip/pynq_Conv_0_0/constraints/Conv_ooc.xdc

# XDC: bd/pynq/ip/pynq_Pool_0_0/constraints/Pool_ooc.xdc

# XDC: bd/pynq/ip/pynq_rst_ps7_0_50M_0/pynq_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==pynq_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynq/ip/pynq_rst_ps7_0_50M_0/pynq_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==pynq_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0_ooc.xdc

# XDC: bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_auto_us_0 || ORIG_REF_NAME==pynq_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynq/ip/pynq_auto_us_0/pynq_auto_us_0_ooc.xdc

# XDC: bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1_ooc.xdc

# XDC: bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynq_auto_us_1 || ORIG_REF_NAME==pynq_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynq/ip/pynq_auto_us_1/pynq_auto_us_1_ooc.xdc

# XDC: bd/pynq/ip/pynq_auto_pc_2/pynq_auto_pc_2_ooc.xdc

# XDC: bd/pynq/pynq_ooc.xdc
