// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __Conv_fmul_32ns_32ns_32_1_max_dsp__HH__
#define __Conv_fmul_32ns_32ns_32_1_max_dsp__HH__
#include "ACMP_fmul_comb.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int din1_WIDTH,
    int dout_WIDTH>
SC_MODULE(Conv_fmul_32ns_32ns_32_1_max_dsp) {
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_in< sc_dt::sc_lv<din1_WIDTH> >   din1;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    ACMP_fmul_comb<ID, 1, din0_WIDTH, din1_WIDTH, dout_WIDTH> ACMP_fmul_comb_U;

    SC_CTOR(Conv_fmul_32ns_32ns_32_1_max_dsp):  ACMP_fmul_comb_U ("ACMP_fmul_comb_U") {
        ACMP_fmul_comb_U.din0(din0);
        ACMP_fmul_comb_U.din1(din1);
        ACMP_fmul_comb_U.dout(dout);

    }

};

#endif //
