// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __Pool_sitofp_32ns_32_1__HH__
#define __Pool_sitofp_32ns_32_1__HH__
#include "ACMP_sitofp_comb.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int dout_WIDTH>
SC_MODULE(Pool_sitofp_32ns_32_1) {
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    ACMP_sitofp_comb<ID, 1, din0_WIDTH, dout_WIDTH> ACMP_sitofp_comb_U;

    SC_CTOR(Pool_sitofp_32ns_32_1):  ACMP_sitofp_comb_U ("ACMP_sitofp_comb_U") {
        ACMP_sitofp_comb_U.din0(din0);
        ACMP_sitofp_comb_U.dout(dout);

    }

};

#endif //
