######################################################################
#
# File name : pynq_wrapper_compile.do
# Created on: Sun Aug 16 02:28:47 +0100 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  "+incdir+../../../../../pynq.srcs/sources_1/bd/pynq/ipshared/ec67/hdl" "+incdir+../../../../../pynq.srcs/sources_1/bd/pynq/ipshared/6b56/hdl" "+incdir+C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
"pynq_wrapper_func_synth.v" \


quit -force

